# ANN001 Missing type annotation for function argument
# ANN002 Missing type annotation for `*args`
# ANN003 Missing type annotation for `**kwargs`
# ANN201 Missing return type annotation for public function
# ANN202 Missing return type annotation for private function
# FA102 future-required-type-annotation
# PLC0415 import-outside-top-level
# PLR0913 too-many-arguments (of function definition)
# PLR0917 too-many-positional-arguments (of function definition)
# PLR2004 magic-value-comparison (unnamed numerical constants ("magic") values)
# PLR6301 Method could be a function, class method, or static method
# PLW0603 (checks for use of) global-statement
# RET505 [*] Unnecessary `elif`/'else' after `return` statement
# RUF067 `__init__` module should only contain docstrings and re-exports
# S107 hardcoded-password-default
# S113 Probable use of `requests` call without timeout
# S606 start-process-with-no-shell

lint.ignore = ["ANN001", "ANN002", "ANN003", "ANN201", "ANN202", "FA102", "PLR0913", "PLR0917", "PLR2004", "PLR6301", "PLW0603", "RET505", "RUF067", "S107", "S113", "S606"]

[lint.per-file-ignores]
"tests/testsuite.py" = [ "PLC0415",]
