---

name: actinia tests

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Start containers
      run: docker compose -f "docker/docker-compose.yml" up -d --build
    - name: List running docker
      run: docker ps
    - name: Docker logs actinia-ogc-api-processes-plugin
      run: docker logs docker-actinia-ogc-api-processes-1
    - name: Docker logs actinia-core
      run: docker logs docker-actinia-core-1
    - name: Run integration test
      run: docker exec -t docker-actinia-ogc-api-processes-1 make test
    - name: Stop containers
      run: docker compose -f "docker/docker-compose.yml" down
